### ISSUE TITLE
网关地址提取多了*号

### ISSUE THREAD

**Issue by here-ted** [houxinlin/cool-request#83]
网关路由配置:
```
- id: api-account
          uri: lb://api-account
          predicates:
            - Path=${server.api.source}/api-account/**
```
cool-request 请求的Environment选择api-account, 地址变成:`http://localhost:8200/h5/api-account/**/login`
正确地址应该是:`http://localhost:8200/h5/api-account/login`
